"""Initial schema for unified database

Revision ID: 7aeeb5420f00
Revises: 
Create Date: 2025-12-07 16:16:05.733967

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aeeb5420f00"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tokens",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "user_email", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("is_authenticated", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_authenticated_at", sa.DateTime(), nullable=True),
        sa.Column("auth_expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "idx_agent_tokens_token_hash", "agent_tokens", ["token_hash"], unique=False
    )
    op.create_index(
        op.f("ix_agent_tokens_is_active"), "agent_tokens", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_agent_tokens_user_id"), "agent_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "pending_authorizations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "sso_state", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "user_email", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "confirmation_code_hash",
            sqlmodel.sql.sqltypes.AutoString(length=256),
            nullable=False,
        ),
        sa.Column("attempts_remaining", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "client_ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sso_state"),
    )
    op.create_index(
        "idx_pending_auth_sso_state",
        "pending_authorizations",
        ["sso_state"],
        unique=False,
    )
    op.create_table(
        "rate_limits",
        sa.Column(
            "identifier", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=False),
        sa.Column("blocked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_table(
        "schema_version",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "session_summaries",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "tenant_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column(
            "project_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column(
            "project_root", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column(
            "session_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("session_start", sa.DateTime(), nullable=False),
        sa.Column(
            "client_agent", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column(
            "backend_model",
            sqlmodel.sql.sqltypes.AutoString(length=256),
            nullable=False,
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "scope", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("goals", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("modified_files", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remaining_tasks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("git_operations", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "operations_performed", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("open_questions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tests_run", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("errors", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key_decisions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "risks_or_warnings", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "branch", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
        sa.Column(
            "head_sha", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "completion_status",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("full_analysis", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "summary_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_session_summaries_session_start",
        "session_summaries",
        ["session_start"],
        unique=False,
    )
    op.create_index(
        "idx_session_summaries_user_project",
        "session_summaries",
        ["user_id", "project_id", "session_start"],
        unique=False,
    )
    op.create_index(
        "idx_session_summaries_user_session_start",
        "session_summaries",
        ["user_id", "session_start"],
        unique=False,
    )
    op.create_index(
        "idx_session_summaries_user_tenant",
        "session_summaries",
        ["user_id", "tenant_id", "session_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_summaries_user_id"),
        "session_summaries",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sso_login_tokens",
        sa.Column(
            "token", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "agent_token_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        "idx_login_token_agent_token",
        "sso_login_tokens",
        ["agent_token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sso_login_tokens_agent_token_id"),
        "sso_login_tokens",
        ["agent_token_id"],
        unique=False,
    )
    op.create_table(
        "user_project_dirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "project_root",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_project_dirs_unique",
        "user_project_dirs",
        ["user_id", "project_root"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_project_dirs_unique", table_name="user_project_dirs")
    op.drop_table("user_project_dirs")
    op.drop_index(
        op.f("ix_sso_login_tokens_agent_token_id"), table_name="sso_login_tokens"
    )
    op.drop_index("idx_login_token_agent_token", table_name="sso_login_tokens")
    op.drop_table("sso_login_tokens")
    op.drop_index(op.f("ix_session_summaries_user_id"), table_name="session_summaries")
    op.drop_index("idx_session_summaries_user_tenant", table_name="session_summaries")
    op.drop_index(
        "idx_session_summaries_user_session_start", table_name="session_summaries"
    )
    op.drop_index("idx_session_summaries_user_project", table_name="session_summaries")
    op.drop_index("idx_session_summaries_session_start", table_name="session_summaries")
    op.drop_table("session_summaries")
    op.drop_table("schema_version")
    op.drop_table("rate_limits")
    op.drop_index("idx_pending_auth_sso_state", table_name="pending_authorizations")
    op.drop_table("pending_authorizations")
    op.drop_index(op.f("ix_agent_tokens_user_id"), table_name="agent_tokens")
    op.drop_index(op.f("ix_agent_tokens_is_active"), table_name="agent_tokens")
    op.drop_index("idx_agent_tokens_token_hash", table_name="agent_tokens")
    op.drop_table("agent_tokens")
    # ### end Alembic commands ###
