[project]
name = "llm-interactive-proxy"
version = "0.1.0"
description = "A short description of my project."
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
dependencies = [
    "pytest",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = { where = ["src"] }

[tool.pytest.ini_options]
pythonpath = "src"
