[project]
name = "llm-interactive-proxy"
version = "0.1.0"
description = "A short description of my project."
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "python-dotenv",
    "pydantic>=2",
    "openai==1.84.0",
    "tomli",
    "typer",
    "rich",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-httpx",
    "ruff",
    "black",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = "."

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-httpx = "^0.35.0"
pytest-asyncio = "^1.0.0"
