[project]
name = "llm-interactive-proxy"
version = "0.1.0"
description = "A short description of my project." # Pyroma might suggest a longer one, but this is fine for now.
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "python-dotenv",
    "pydantic>=2",
    "openai==1.84.0",
    "tomli",
    "typer",
    "rich",
    "llm-accounting",
    "tiktoken",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" } # License specified here
keywords = ["llm", "proxy", "interactive", "api", "ai", "chatgpt", "openai", "gemini", "openrouter"]
urls = { Home = "https://github.com/example-user/llm-interactive-proxy" } # Example URL
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License", # License classifier added
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Internet :: Proxy Servers",
    "Operating System :: OS Independent", # Common classifier
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-httpx",
    "ruff",
    "black",
    "google-genai",  # Official Google Gemini API client for integration tests
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = "."
