"""Fallback catalog loader.

Loads the shipped fallback catalog snapshot (or an operator override path) and
parses it with :class:`CodexCatalogParser`. The shipped snapshot lives at
``src/resources/codex/codex_model_catalog.json`` and is the verbatim output of
``codex debug models`` (regenerated by ``scripts/refresh_codex_model_catalog.py``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

from src.connectors.openai_codex.catalog.interfaces import ICodexCatalogParser
from src.connectors.openai_codex.catalog.parser import CodexCatalogParser
from src.connectors.openai_codex.catalog.types import CodexModelCatalog

SHIPPED_RESOURCE_PACKAGE = "src.resources.codex"
SHIPPED_RESOURCE_NAME = "codex_model_catalog.json"


class CodexCatalogFallbackLoader:
    """Load the fallback catalog JSON from a shipped resource or override path."""

    def __init__(
        self,
        *,
        fallback_path: str | None = None,
        parser: ICodexCatalogParser | None = None,
    ) -> None:
        self._fallback_path = self._normalize_path(fallback_path)
        self._parser = parser if parser is not None else CodexCatalogParser()

    @staticmethod
    def _normalize_path(fallback_path: str | None) -> str | None:
        if isinstance(fallback_path, str) and fallback_path.strip():
            return fallback_path.strip()
        return None

    def load(self) -> CodexModelCatalog:
        raw = self._read_raw_json()
        return self._parser.parse(raw)

    def _read_raw_json(self) -> dict[str, Any]:
        if self._fallback_path is not None:
            text = Path(self._fallback_path).read_text(encoding="utf-8")
        else:
            text = self._read_shipped_resource()
        return cast(dict[str, Any], json.loads(text))

    @staticmethod
    def _read_shipped_resource() -> str:
        from importlib import resources as importlib_resources

        return importlib_resources.read_text(
            SHIPPED_RESOURCE_PACKAGE,
            SHIPPED_RESOURCE_NAME,
            encoding="utf-8",
        )


__all__ = [
    "CodexCatalogFallbackLoader",
    "SHIPPED_RESOURCE_NAME",
    "SHIPPED_RESOURCE_PACKAGE",
]
