"""Property-based tests for SSO sandbox handler.

Feature: sso-authentication
Properties: 5, 26
Validates: Requirements 2.4, 10.1, 10.2, 10.4, 10.5
"""

from __future__ import annotations

import json

from hypothesis import given
from hypothesis import strategies as st
from src.core.auth.sso.sandbox_handler import SandboxHandler
from tests.utils.hypothesis_config import property_test_settings


# Strategy for generating valid URLs
@st.composite
def url_strategy(draw: st.DrawFn) -> str:
    """Generate valid HTTP/HTTPS URLs."""
    protocol = draw(st.sampled_from(["http", "https"]))
    domain = draw(
        st.text(
            alphabet=st.characters(
                whitelist_categories=("Ll", "Nd"), whitelist_characters="-"
            ),
            min_size=3,
            max_size=20,
        )
    )
    tld = draw(st.sampled_from(["com", "org", "net", "io", "dev"]))
    path = draw(
        st.one_of(
            st.just(""),
            st.text(
                alphabet=st.characters(
                    whitelist_categories=("Ll", "Nd"), whitelist_characters="/-_"
                ),
                min_size=1,
                max_size=50,
            ).map(lambda p: f"/{p}"),
        )
    )

    return f"{protocol}://{domain}.{tld}{path}"


@given(auth_url=url_strategy())
@property_test_settings()
async def test_property_5_sandbox_response_format_validity(
    auth_url: str,
) -> None:
    """
    Property 5: Sandbox Response Format Validity.

    For any sandbox response generated by the proxy, the response SHALL be
    a valid OpenAI-compatible chat completion response that can be parsed
    by standard clients.

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler(auth_url)
    response = await handler.generate_login_banner()

    # Verify response is a dictionary
    assert isinstance(response, dict), "Response should be a dictionary"

    # Verify required top-level fields
    assert "id" in response, "Response should have 'id' field"
    assert "object" in response, "Response should have 'object' field"
    assert "created" in response, "Response should have 'created' field"
    assert "model" in response, "Response should have 'model' field"
    assert "choices" in response, "Response should have 'choices' field"
    assert "usage" in response, "Response should have 'usage' field"

    # Verify object type
    assert (
        response["object"] == "chat.completion"
    ), "Object type should be 'chat.completion'"

    # Verify created is an integer timestamp
    assert isinstance(response["created"], int), "Created should be an integer"
    assert response["created"] > 0, "Created timestamp should be positive"

    # Verify model is a string
    assert isinstance(response["model"], str), "Model should be a string"
    assert len(response["model"]) > 0, "Model should not be empty"

    # Verify choices is a list
    assert isinstance(response["choices"], list), "Choices should be a list"
    assert len(response["choices"]) > 0, "Choices should not be empty"

    # Verify first choice structure
    choice = response["choices"][0]
    assert isinstance(choice, dict), "Choice should be a dictionary"
    assert "index" in choice, "Choice should have 'index' field"
    assert "message" in choice, "Choice should have 'message' field"
    assert "finish_reason" in choice, "Choice should have 'finish_reason' field"

    # Verify choice index
    assert choice["index"] == 0, "First choice index should be 0"

    # Verify message structure
    message = choice["message"]
    assert isinstance(message, dict), "Message should be a dictionary"
    assert "role" in message, "Message should have 'role' field"
    assert "content" in message, "Message should have 'content' field"

    # Verify message role
    assert message["role"] == "assistant", "Message role should be 'assistant'"

    # Verify message content
    assert isinstance(message["content"], str), "Message content should be a string"
    assert len(message["content"]) > 0, "Message content should not be empty"

    # Verify finish reason
    assert isinstance(choice["finish_reason"], str), "Finish reason should be a string"
    assert choice["finish_reason"] == "stop", "Finish reason should be 'stop'"

    # Verify usage structure
    usage = response["usage"]
    assert isinstance(usage, dict), "Usage should be a dictionary"
    assert "prompt_tokens" in usage, "Usage should have 'prompt_tokens' field"
    assert "completion_tokens" in usage, "Usage should have 'completion_tokens' field"
    assert "total_tokens" in usage, "Usage should have 'total_tokens' field"

    # Verify usage values are integers
    assert isinstance(usage["prompt_tokens"], int), "Prompt tokens should be an integer"
    assert isinstance(
        usage["completion_tokens"], int
    ), "Completion tokens should be an integer"
    assert isinstance(usage["total_tokens"], int), "Total tokens should be an integer"

    # Verify usage values are non-negative
    assert usage["prompt_tokens"] >= 0, "Prompt tokens should be non-negative"
    assert usage["completion_tokens"] >= 0, "Completion tokens should be non-negative"
    assert usage["total_tokens"] >= 0, "Total tokens should be non-negative"


@given(auth_url=url_strategy())
@property_test_settings()
async def test_property_5_sandbox_response_json_serializable(
    auth_url: str,
) -> None:
    """
    Property 5: Sandbox response JSON serializability.

    For any sandbox response, the response SHALL be JSON-serializable
    (can be converted to JSON and back without errors).

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler(auth_url)
    response = await handler.generate_login_banner()

    # Verify response can be serialized to JSON
    try:
        json_str = json.dumps(response)
    except (TypeError, ValueError) as e:
        raise AssertionError(f"Response should be JSON-serializable: {e}") from e

    # Verify response can be deserialized from JSON
    try:
        deserialized = json.loads(json_str)
    except (TypeError, ValueError) as e:
        raise AssertionError(f"Response should be JSON-deserializable: {e}") from e

    # Verify deserialized response matches original
    assert (
        deserialized == response
    ), "Deserialized response should match original response"


@given(auth_url=url_strategy())
@property_test_settings()
async def test_property_5_sandbox_response_contains_auth_url(
    auth_url: str,
) -> None:
    """
    Property 5: Sandbox response contains authentication URL.

    For any sandbox response, the message content SHALL contain the
    authentication URL provided to the handler.

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler(auth_url)
    response = await handler.generate_login_banner()

    # Extract message content
    message_content = response["choices"][0]["message"]["content"]

    # Verify auth URL is present in message content
    assert (
        auth_url in message_content
    ), f"Message content should contain auth URL: {auth_url}"


@given(auth_url=url_strategy())
@property_test_settings()
async def test_property_5_sandbox_response_contains_instructions(
    auth_url: str,
) -> None:
    """
    Property 5: Sandbox response contains authentication instructions.

    For any sandbox response, the message content SHALL contain clear
    instructions for the user to authenticate.

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler(auth_url)
    response = await handler.generate_login_banner()

    # Extract message content
    message_content = response["choices"][0]["message"]["content"]

    # Verify key instruction elements are present
    required_elements = [
        "Authentication Required",
        "authenticate",
        "token",
        "agent",
    ]

    for element in required_elements:
        assert (
            element.lower() in message_content.lower()
        ), f"Message should contain '{element}'"


@given(
    messages=st.lists(
        st.fixed_dictionaries(
            {
                "role": st.sampled_from(["user", "assistant", "system"]),
                "content": st.text(min_size=0, max_size=500),
            }
        ),
        min_size=1,
        max_size=20,
    )
)
@property_test_settings()
def test_property_26_sandbox_session_isolation_no_sandbox_content(
    messages: list[dict[str, str]],
) -> None:
    """
    Property 26: Sandbox Session Isolation (no sandbox content).

    For any conversation history that does NOT contain sandbox content,
    the sandbox history detection SHALL return False.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler("https://example.com/auth")

    # Verify no sandbox content is detected in regular messages
    result = handler.detect_sandbox_history(messages)

    # If none of the messages contain sandbox markers, result should be False
    has_sandbox_marker = any(
        "Authentication Required" in msg.get("content", "")
        or "chatcmpl-sandbox" in msg.get("content", "")
        for msg in messages
    )

    if not has_sandbox_marker:
        assert result is False, "Should not detect sandbox content in regular messages"


@given(
    auth_url=url_strategy(),
    prefix_messages=st.lists(
        st.fixed_dictionaries(
            {
                "role": st.sampled_from(["user", "assistant"]),
                "content": st.text(
                    alphabet=st.characters(
                        blacklist_characters="Authentication Required"
                    ),
                    min_size=0,
                    max_size=100,
                ),
            }
        ),
        min_size=0,
        max_size=5,
    ),
    suffix_messages=st.lists(
        st.fixed_dictionaries(
            {
                "role": st.sampled_from(["user", "assistant"]),
                "content": st.text(min_size=0, max_size=100),
            }
        ),
        min_size=0,
        max_size=5,
    ),
)
@property_test_settings()
async def test_property_26_sandbox_session_isolation_with_sandbox_content(
    auth_url: str,
    prefix_messages: list[dict[str, str]],
    suffix_messages: list[dict[str, str]],
) -> None:
    """
    Property 26: Sandbox Session Isolation (with sandbox content).

    For any conversation history that contains a sandbox login banner,
    the sandbox history detection SHALL return True, regardless of where
    the sandbox content appears in the history.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler(auth_url)

    # Generate a sandbox response
    sandbox_response = await handler.generate_login_banner()
    sandbox_message = {
        "role": "assistant",
        "content": sandbox_response["choices"][0]["message"]["content"],
        "id": sandbox_response["id"],
    }

    # Create conversation history with sandbox content in the middle
    messages = [*prefix_messages, sandbox_message, *suffix_messages]

    # Verify sandbox content is detected
    result = handler.detect_sandbox_history(messages)
    assert result is True, "Should detect sandbox content when login banner is present"


@given(auth_url=url_strategy())
@property_test_settings()
def test_property_26_sandbox_session_isolation_sandbox_id_detection(
    auth_url: str,
) -> None:
    """
    Property 26: Sandbox session isolation via ID detection.

    For any message with the sandbox completion ID, the sandbox history
    detection SHALL return True.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler(auth_url)

    # Create a message with sandbox ID but different content
    messages = [
        {
            "role": "assistant",
            "content": "Some other content",
            "id": "chatcmpl-sandbox",
        }
    ]

    # Verify sandbox content is detected via ID
    result = handler.detect_sandbox_history(messages)
    assert result is True, "Should detect sandbox content via completion ID"


@given(
    auth_url=url_strategy(),
    num_messages=st.integers(min_value=1, max_value=50),
)
@property_test_settings()
def test_property_26_sandbox_session_isolation_marker_detection(
    auth_url: str,
    num_messages: int,
) -> None:
    """
    Property 26: Sandbox session isolation via marker detection.

    For any conversation history containing sandbox marker text, the
    sandbox history detection SHALL return True.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler(auth_url)

    # Create messages with sandbox marker in one of them
    messages = [
        {"role": "user", "content": f"Message {i}"} for i in range(num_messages - 1)
    ]

    # Add a message with sandbox marker
    messages.append(
        {
            "role": "assistant",
            "content": "# Authentication Required\nPlease authenticate to continue.",
        }
    )

    # Verify sandbox content is detected
    result = handler.detect_sandbox_history(messages)
    assert result is True, "Should detect sandbox content via marker text"


@given(
    auth_url=url_strategy(),
    override_url=url_strategy(),
)
@property_test_settings(max_examples=15)
async def test_property_5_sandbox_response_url_override(
    auth_url: str,
    override_url: str,
) -> None:
    """
    Property 5: Sandbox response URL override.

    For any sandbox handler with a default auth URL, when generating a
    login banner with an override URL, the response SHALL contain the
    override URL instead of the default.

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler(auth_url)

    # Generate banner with override URL
    response = await handler.generate_login_banner(override_url)

    # Extract message content
    message_content = response["choices"][0]["message"]["content"]

    # Verify override URL is present
    assert (
        override_url in message_content
    ), f"Message should contain override URL: {override_url}"

    # Verify default URL is NOT present (if different and not a substring)
    # Only check if auth_url is not a substring of override_url
    if override_url != auth_url and auth_url not in override_url:
        assert (
            auth_url not in message_content
        ), f"Message should not contain default URL when override is provided: {auth_url}"


@given(message=st.text(min_size=1, max_size=1000))
@property_test_settings()
def test_property_5_format_as_completion_response_structure(
    message: str,
) -> None:
    """
    Property 5: Format as completion response structure.

    For any message text, the format_as_completion_response method SHALL
    produce a valid OpenAI-compatible chat completion response.

    Validates: Requirements 2.4

    Feature: sso-authentication, Property 5: Sandbox Response Format Validity
    """
    handler = SandboxHandler("https://example.com/auth")
    response = handler.format_as_completion_response(message)

    # Verify response structure
    assert isinstance(response, dict), "Response should be a dictionary"
    assert "id" in response, "Response should have 'id' field"
    assert "object" in response, "Response should have 'object' field"
    assert "created" in response, "Response should have 'created' field"
    assert "model" in response, "Response should have 'model' field"
    assert "choices" in response, "Response should have 'choices' field"
    assert "usage" in response, "Response should have 'usage' field"

    # Verify message content matches input
    assert (
        response["choices"][0]["message"]["content"] == message
    ), "Response content should match input message"


@given(
    messages=st.lists(
        st.fixed_dictionaries(
            {
                "role": st.sampled_from(["user", "assistant", "system"]),
                "content": st.text(min_size=0, max_size=200),
            }
        ),
        min_size=0,
        max_size=10,
    )
)
@property_test_settings()
def test_property_26_sandbox_session_isolation_empty_messages(
    messages: list[dict[str, str]],
) -> None:
    """
    Property 26: Sandbox session isolation with empty messages.

    For any conversation history with empty content, the sandbox history
    detection SHALL handle it gracefully without errors.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler("https://example.com/auth")

    # Should not raise any exceptions
    try:
        result = handler.detect_sandbox_history(messages)
        # Result should be boolean
        assert isinstance(result, bool), "Result should be a boolean"
    except Exception as e:
        raise AssertionError(f"Should handle empty messages gracefully: {e}") from e


@given(
    messages=st.lists(
        st.fixed_dictionaries(
            {
                "role": st.sampled_from(["user", "assistant", "system"]),
                "content": st.one_of(
                    st.none(),
                    st.text(min_size=0, max_size=100),
                ),
            }
        ),
        min_size=0,
        max_size=10,
    )
)
@property_test_settings()
def test_property_26_sandbox_session_isolation_none_content(
    messages: list[dict[str, str]],
) -> None:
    """
    Property 26: Sandbox session isolation with None content.

    For any conversation history with None content values, the sandbox
    history detection SHALL handle it gracefully without errors.

    Validates: Requirements 10.1, 10.2, 10.4, 10.5

    Feature: sso-authentication, Property 26: Sandbox Session Isolation
    """
    handler = SandboxHandler("https://example.com/auth")

    # Should not raise any exceptions
    try:
        result = handler.detect_sandbox_history(messages)
        # Result should be boolean
        assert isinstance(result, bool), "Result should be a boolean"
    except Exception as e:
        raise AssertionError(f"Should handle None content gracefully: {e}") from e
