"""Integration tests for empty response prevention.

These tests ensure that errors are properly propagated to clients and that
empty responses with HTTP 200 status codes never occur when there are errors.
"""

import json
from typing import Any, cast

import pytest
from src.core.common.exceptions import BackendError
from src.core.interfaces.response_processor_interface import ProcessedResponse
from src.core.ports.sse_assembler import SSEAssembler
from src.core.ports.streaming_contracts import StreamingContent


class TestErrorStreamPrevention:
    """Tests ensuring errors are properly streamed, not empty responses."""

    @pytest.mark.asyncio
    async def test_rate_limit_error_returns_error_chunk_not_empty(self) -> None:
        """When a rate limit error occurs, client should receive error chunk, not empty."""
        # Create error chunk as it would be generated by the backend
        error_chunk = ProcessedResponse(
            content={
                "id": "chatcmpl-error-123",
                "object": "chat.completion.chunk",
                "created": 1234567890,
                "model": "gemini-2.5-pro",
                "choices": [{"index": 0, "delta": {}, "finish_reason": "error"}],
                "error": {
                    "message": "Rate limit exceeded. Please try again later.",
                    "type": "rate_limit_exceeded",
                    "code": 429,
                },
            },
            metadata={
                "finish_reason": "error",
                "error": {
                    "message": "Rate limit exceeded. Please try again later.",
                    "type": "rate_limit_exceeded",
                    "code": 429,
                },
                "id": "chatcmpl-error-123",
                "model": "gemini-2.5-pro",
                "created": 1234567890,
            },
        )

        # Convert to StreamingContent
        content = StreamingContent(
            content=cast(dict[str, Any], error_chunk.content),
            metadata=error_chunk.metadata,
            is_done=True,
        )

        # Serialize to bytes
        result = content.to_bytes()
        decoded = result.decode("utf-8")

        # Should not be empty
        assert len(decoded) > 0
        assert "data:" in decoded

        # Should contain error information
        assert "error" in decoded
        assert "rate_limit" in decoded.lower() or "Rate limit" in decoded

    @pytest.mark.asyncio
    async def test_quota_exhausted_returns_clear_error_message(self) -> None:
        """When quota is exhausted, client should receive clear error message."""
        error_content = {
            "id": "chatcmpl-error-456",
            "object": "chat.completion.chunk",
            "created": 1234567890,
            "model": "claude-sonnet-4-5",
            "choices": [{"index": 0, "delta": {}, "finish_reason": "error"}],
            "error": {
                "message": "Quota exhausted. Your quota will reset after 3h20m.",
                "type": "quota_exceeded",
                "code": 503,
            },
        }

        content = StreamingContent(
            content=error_content,
            metadata={
                "finish_reason": "error",
                "error": error_content["error"],
                "id": error_content["id"],
                "model": error_content["model"],
                "created": error_content["created"],
            },
            is_done=True,
        )

        result = content.to_bytes()
        decoded = result.decode("utf-8")

        # Extract JSON from SSE data
        lines = decoded.strip().split("\n")
        data_lines = [
            line for line in lines if line.startswith("data:") and "[DONE]" not in line
        ]

        assert len(data_lines) > 0
        json_str = data_lines[0][5:].strip()  # Remove "data:" prefix
        payload = json.loads(json_str)

        # Verify error details are present
        assert "error" in payload
        assert payload["error"]["type"] == "quota_exceeded"
        assert "Quota exhausted" in payload["error"]["message"]

    @pytest.mark.asyncio
    async def test_backend_error_propagates_to_client(self) -> None:
        """Backend errors must propagate to the client with details."""
        error = BackendError(
            message="Backend unavailable: connection refused",
            code="backend_unavailable",
            status_code=502,
        )

        # Simulate how the error would be handled
        from src.core.ports.streaming_contracts import handle_streaming_error

        chunk = await handle_streaming_error(
            error, stream_id="test-stream", provider="test-backend"
        )

        # Verify the chunk is properly formed
        assert chunk.is_done is True
        assert chunk.metadata["finish_reason"] == "error"
        assert "error" in chunk.metadata
        assert "Backend unavailable" in chunk.metadata["error"]["message"]

    @pytest.mark.asyncio
    async def test_error_stream_includes_error_field(self) -> None:
        """Error streams must include the error field in all error chunks."""

        async def mock_error_stream():
            """Simulates a stream that ends with an error."""
            # Normal content chunk
            yield StreamingContent(
                content={"choices": [{"delta": {"content": "Hello"}}]},
                metadata={"role": "assistant"},
                is_done=False,
            )
            # Error chunk
            yield StreamingContent(
                content="",
                metadata={
                    "finish_reason": "error",
                    "error": {
                        "message": "Stream interrupted",
                        "type": "stream_error",
                        "code": 500,
                    },
                },
                is_done=True,
            )

        # Process the stream through SSEAssembler
        assembler = SSEAssembler()
        chunks = []
        async for chunk in assembler.assemble_stream(mock_error_stream(), format="sse"):
            chunks.append(chunk)

        # Combine all chunks
        combined = b"".join(chunks)
        decoded = combined.decode("utf-8")

        # Should contain the error information
        assert "error" in decoded or "stream_error" in decoded or "[DONE]" in decoded

    @pytest.mark.asyncio
    async def test_empty_terminal_delta_emits_only_done(self) -> None:
        """Final chunks without assistant content should not stream empty messages."""

        content = StreamingContent(
            content={
                "id": "chatcmpl-empty-123",
                "object": "chat.completion.chunk",
                "created": 123,
                "model": "code-assist-model",
                "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
            },
            metadata={"finish_reason": "stop"},
            is_done=True,
        )

        result = content.to_bytes().decode("utf-8")

        assert result == "data: [DONE]\n\n"
        assert "delta" not in result


class TestMultiModelRateLimiting:
    """Tests ensuring rate limiting for one model doesn't block others."""

    @pytest.mark.asyncio
    async def test_model_a_rate_limit_does_not_block_model_b(self) -> None:
        """Rate limiting model A should not prevent requests to model B."""
        from src.connectors.gemini_oauth_base import (
            ModelRetryState,
        )

        # Create mock retry states
        retry_states: dict[str, ModelRetryState] = {}

        # Simulate model A in cooldown
        model_a_state = ModelRetryState()
        model_a_state.cooldown_until = float("inf")  # Never expires
        retry_states["model-a"] = model_a_state

        # Model B should not be in cooldown
        assert "model-b" not in retry_states

        # Check cooldown logic
        def is_in_cooldown(model: str) -> bool:
            state = retry_states.get(model)
            if not state:
                return False
            import time

            return time.time() < state.cooldown_until

        # Model A is in cooldown
        assert is_in_cooldown("model-a") is True
        # Model B is NOT in cooldown
        assert is_in_cooldown("model-b") is False

    @pytest.mark.asyncio
    async def test_switching_models_after_rate_limit(self) -> None:
        """After one model is rate limited, switching to another should work."""
        # This tests the logical flow, not actual network calls
        # Simulate the degradation flow
        models_tried = []
        models_in_cooldown = {"gemini-2.5-pro"}

        def try_model(model: str) -> bool:
            """Simulate trying a model."""
            models_tried.append(model)
            return model not in models_in_cooldown

        # First try fails (in cooldown)
        result = try_model("gemini-2.5-pro")
        assert result is False

        # Second try succeeds (not in cooldown)
        result = try_model("gemini-2.5-flash")
        assert result is True

        # Both models were tried
        assert "gemini-2.5-pro" in models_tried
        assert "gemini-2.5-flash" in models_tried


class TestProcessedResponseMetadata:
    """Tests for ProcessedResponse metadata handling."""

    def test_processed_response_with_error_metadata(self) -> None:
        """ProcessedResponse should preserve error metadata."""
        error_content = {
            "id": "chatcmpl-error-789",
            "object": "chat.completion.chunk",
            "created": 1234567890,
            "model": "test-model",
            "choices": [{"index": 0, "delta": {}, "finish_reason": "error"}],
            "error": {
                "message": "Test error",
                "type": "test_error",
                "code": 500,
            },
        }

        response = ProcessedResponse(
            content=error_content,
            metadata={
                "finish_reason": "error",
                "error": error_content["error"],
                "id": error_content["id"],
                "model": error_content["model"],
                "created": error_content["created"],
            },
        )

        # Verify metadata is preserved
        assert response.metadata is not None
        assert response.metadata["finish_reason"] == "error"
        assert response.metadata["error"]["message"] == "Test error"
        assert response.metadata["error"]["type"] == "test_error"
        assert response.metadata["error"]["code"] == 500

    def test_processed_response_without_metadata_still_has_content(self) -> None:
        """ProcessedResponse without metadata should still have accessible content."""
        error_content = {
            "error": {
                "message": "Error in content only",
                "type": "content_error",
                "code": 400,
            }
        }

        response = ProcessedResponse(content=error_content)

        # Content should be accessible even without metadata
        assert response.content is not None
        assert response.content["error"]["message"] == "Error in content only"


class TestEmptyResponseDetection:
    """Tests for detecting and preventing empty responses."""

    def test_empty_streaming_content_detection(self) -> None:
        """Empty StreamingContent should be detectable."""
        empty_chunk = StreamingContent(content="", metadata={}, is_done=False)
        non_empty_chunk = StreamingContent(
            content={"choices": [{"delta": {"content": "Hello"}}]},
            metadata={},
            is_done=False,
        )

        assert empty_chunk.is_empty is True
        assert non_empty_chunk.is_empty is False

    def test_error_chunk_not_considered_empty(self) -> None:
        """Error chunks should not be considered empty even with no content."""
        error_chunk = StreamingContent(
            content="",
            metadata={
                "finish_reason": "error",
                "error": {"message": "Error", "type": "error", "code": 500},
            },
            is_done=True,
            is_empty=False,
        )

        # Error chunks are marked is_done=True, which means they should be processed
        assert error_chunk.is_done is True
        # The explicit is_empty=False means it won't be skipped
        assert error_chunk.is_empty is False

    def test_done_marker_handling(self) -> None:
        """Done markers should be properly identified."""
        done_chunk = StreamingContent(content="[DONE]", metadata={}, is_done=True)

        assert done_chunk.is_done is True
