$schema: "http://json-schema.org/draft-07/schema#"
title: App Config
type: object
additionalProperties: false
properties:
  host: { type: string }
  port: { type: integer, minimum: 1 }
  anthropic_port: { type: integer, minimum: 1 }
  proxy_timeout: { type: integer, minimum: 0 }
  command_prefix: { type: string }
  strict_command_detection: { type: boolean }
  context_window_override: { type: ["integer", "null"], minimum: 1 }
  default_rate_limit: { type: integer, minimum: 0 }
  default_rate_window: { type: integer, minimum: 0 }
  model_defaults: { type: object, additionalProperties: true }
  failover_routes: { type: object, additionalProperties: true }
  identity: { type: object, additionalProperties: true }
  empty_response: { type: object, additionalProperties: true }
  edit_precision: { type: object, additionalProperties: true }
  rewriting: { type: object, additionalProperties: true }
  app: { type: ["object", "null"] }
  logging:
    type: object
    additionalProperties: false
    properties:
      level: { type: string, enum: [DEBUG, INFO, WARNING, ERROR, CRITICAL] }
      request_logging: { type: boolean }
      response_logging: { type: boolean }
      log_file: { type: ["string", "null"] }
      capture_file: { type: ["string", "null"] }
      capture_max_bytes: { type: ["integer", "null"], minimum: 0 }
      capture_truncate_bytes: { type: ["integer", "null"], minimum: 0 }
      capture_max_files: { type: ["integer", "null"], minimum: 0 }
      capture_rotate_interval_seconds: { type: ["integer", "null"], minimum: 0 }
      capture_total_max_bytes: { type: ["integer", "null"], minimum: 0 }
      capture_buffer_size: { type: ["integer", "null"], minimum: 1024 }
      capture_flush_interval: { type: ["number", "null"], minimum: 0.1 }
      capture_max_entries_per_flush: { type: ["integer", "null"], minimum: 1 }
  auth:
    type: object
    additionalProperties: false
    properties:
      disable_auth: { type: boolean }
      api_keys:
        type: array
        items: { type: string }
      auth_token: { type: ["string", "null"] }
      redact_api_keys_in_prompts: { type: boolean }
      trusted_ips:
        type: array
        items: { type: string }
      brute_force_protection:
        type: object
        additionalProperties: false
        properties:
          enabled: { type: boolean }
          max_failed_attempts: { type: integer, minimum: 1 }
          ttl_seconds: { type: integer, minimum: 1 }
          initial_block_seconds: { type: integer, minimum: 1 }
          block_multiplier: { type: number, minimum: 1 }
          max_block_seconds: { type: integer, minimum: 1 }
  session:
    type: object
    additionalProperties: false
    properties:
      cleanup_enabled: { type: boolean }
      cleanup_interval: { type: integer, minimum: 0 }
      max_age: { type: integer, minimum: 0 }
      default_interactive_mode: { type: boolean }
      force_set_project: { type: boolean }
      disable_interactive_commands: { type: boolean }
      tool_call_repair_enabled: { type: boolean }
      json_repair_enabled: { type: boolean }
      json_repair_strict_mode: { type: boolean }
      json_repair_schema: { type: ["string", "null"] }
      json_repair_buffer_cap_bytes: { type: integer, minimum: 0 }
      content_accumulation_buffer_cap_bytes: { type: integer, minimum: 0 }
      tool_call_repair_buffer_cap_bytes: { type: integer, minimum: 0 }
      dangerous_command_prevention_enabled: { type: boolean }
      dangerous_command_steering_message: { type: ["string", "null"] }
      pytest_compression_enabled: { type: boolean }
      pytest_compression_min_lines: { type: integer, minimum: 1 }
      pytest_full_suite_steering_enabled: { type: boolean }
      pytest_full_suite_steering_message: { type: ["string", "null"] }
      planning_phase:
        type: object
        additionalProperties: false
        properties:
          enabled: { type: boolean }
          strong_model: { type: ["string", "null"] }
          max_turns: { type: integer, minimum: 1 }
          max_file_writes: { type: integer, minimum: 0 }
          overrides:
            type: ["object", "null"]
            additionalProperties: false
            properties:
              temperature: { type: ["number", "null"] }
              top_p: { type: ["number", "null"] }
              reasoning_effort: { type: ["string", "null"] }
              thinking_budget: { type: ["integer", "null"], minimum: 0 }
              reasoning: { type: ["object", "null"] }
              generation_config: { type: ["object", "null"] }
      tool_call_reactor:
        type: object
        additionalProperties: true
        properties:
          enabled: { type: boolean }
          apply_diff_steering_enabled: { type: boolean }
          apply_diff_steering_rate_limit_seconds: { type: integer, minimum: 0 }
          apply_diff_steering_message: { type: ["string", "null"] }
          pytest_full_suite_steering_enabled: { type: boolean }
          pytest_full_suite_steering_message: { type: ["string", "null"] }
          steering_rules:
            type: array
            items: { type: object }
  backends:
    type: object
    additionalProperties: true
    properties:
      default_backend: { type: string }
  default_backend: { type: string }
  reasoning_aliases:
    type: object
    additionalProperties: true
  model_aliases:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        pattern:
          type: string
        replacement:
          type: string
      required: [pattern, replacement]
    default: []
