$schema: "http://json-schema.org/draft-07/schema#"
title: Edit Precision Patterns
type: object
additionalProperties: false
properties:
  request_patterns:
    type: array
    items:
      type: string
  response_patterns:
    type: array
    items:
      type: string
required: []
