$schema: "http://json-schema.org/draft-07/schema#"
title: ZAI Default Models
type: object
additionalProperties: false
properties:
  models:
    type: array
    items: { type: string }
    minItems: 1
  description:
    type: string
  last_updated:
    type: string
required: [models]
