"""Constants for command output messages.

This module centralizes all the output messages generated by command handlers
to make the test suite less fragile and easier to maintain.
"""

# Backend handler messages
BACKEND_SET_MESSAGE = "Backend set to {backend}"
BACKEND_NOT_SUPPORTED_MESSAGE = "Backend {backend} not supported"
BACKEND_NOT_FUNCTIONAL_MESSAGE = "Backend {backend} not functional (session override unset)"
BACKEND_MUST_BE_STRING_MESSAGE = "Backend value must be a string"

# Model handler messages
MODEL_SET_MESSAGE = "Model set to {model}"
MODEL_UNSET_MESSAGE = "model unset"
MODEL_MUST_BE_STRING_MESSAGE = "Model value must be a string"
MODEL_BACKEND_NOT_SUPPORTED_MESSAGE = "Backend {backend} in model {model} not supported"

# Backend and model combined messages
BACKEND_AND_MODEL_SET_MESSAGE = "Backend set to {backend} with model {model}"

# OpenAI URL handler messages
OPENAI_URL_SET_MESSAGE = "OpenAI URL set to {url}"
OPENAI_URL_MUST_BE_STRING_MESSAGE = "OpenAI URL value must be a string"
OPENAI_URL_MUST_START_WITH_HTTP_MESSAGE = "OpenAI URL must start with http:// or https://"

# Project handler messages
PROJECT_SET_MESSAGE = "Project set to {project}"
PROJECT_UNSET_MESSAGE = "Project unset"

# Loop detection handler messages
LOOP_DETECTION_ENABLED_MESSAGE = "Loop detection enabled"
LOOP_DETECTION_DISABLED_MESSAGE = "Loop detection disabled"
LOOP_DETECTION_BOOLEAN_REQUIRED_MESSAGE = "Boolean value must be specified"
LOOP_DETECTION_INVALID_BOOLEAN_MESSAGE = "Invalid boolean value: {value}"

# Tool loop detection handler messages
TOOL_LOOP_DETECTION_ENABLED_MESSAGE = "Tool call loop detection enabled"
TOOL_LOOP_DETECTION_DISABLED_MESSAGE = "Tool call loop detection disabled"
TOOL_LOOP_DETECTION_BOOLEAN_REQUIRED_MESSAGE = "Boolean value must be specified"
TOOL_LOOP_DETECTION_INVALID_BOOLEAN_MESSAGE = "Invalid boolean value: {value}"

# Tool loop max repeats handler messages
TOOL_LOOP_MAX_REPEATS_SET_MESSAGE = "Tool call loop max repeats set to {max_repeats}"
TOOL_LOOP_MAX_REPEATS_REQUIRED_MESSAGE = "Max repeats value must be specified"
TOOL_LOOP_MAX_REPEATS_MUST_BE_INTEGER_MESSAGE = "Invalid max repeats value: {value}. Must be an integer."
TOOL_LOOP_MAX_REPEATS_AT_LEAST_TWO_MESSAGE = "Max repeats must be at least 2"

# Tool loop TTL handler messages
TOOL_LOOP_TTL_SET_MESSAGE = "Tool call loop TTL set to {ttl} seconds"
TOOL_LOOP_TTL_REQUIRED_MESSAGE = "TTL value must be specified"
TOOL_LOOP_TTL_MUST_BE_INTEGER_MESSAGE = "Invalid TTL value: {value}. Must be an integer."
TOOL_LOOP_TTL_AT_LEAST_ONE_MESSAGE = "TTL must be at least 1 second"

# Tool loop mode handler messages
TOOL_LOOP_MODE_SET_MESSAGE = "Tool call loop mode set to {mode}"
TOOL_LOOP_MODE_REQUIRED_MESSAGE = "Loop mode must be specified"
TOOL_LOOP_MODE_INVALID_MESSAGE = "Invalid loop mode: {value}. Use break or chance_then_break."

# Temperature handler messages
TEMPERATURE_SET_MESSAGE = "Temperature set to {temperature}"
TEMPERATURE_MUST_BE_NUMBER_MESSAGE = "Temperature must be a valid number"
TEMPERATURE_OUT_OF_RANGE_MESSAGE = "Temperature must be between 0.0 and 1.0"

# Oneoff handler messages
ONEOFF_ROUTE_SET_MESSAGE = "One-off route set to {backend}/{model}."
ONEOFF_BACKEND_MODEL_REQUIRED_MESSAGE = "Both backend and model must be specified for oneoff command"

# Failover handlers messages
FAILOVER_ROUTE_CREATED_MESSAGE = "Created failover route: {route_name}"
FAILOVER_ROUTE_DELETED_MESSAGE = "Deleted failover route: {route_name}"
FAILOVER_ROUTE_NOT_FOUND_MESSAGE = "Failover route not found: {route_name}"
FAILOVER_ROUTE_ALREADY_EXISTS_MESSAGE = "Failover route already exists: {route_name}"
FAILOVER_ROUTE_APPENDED_MESSAGE = "Appended {element} to route: {route_name}"
FAILOVER_ROUTE_PREPENDED_MESSAGE = "Prepended {element} to route: {route_name}"
FAILOVER_ROUTE_CLEARED_MESSAGE = "Cleared route: {route_name}"
FAILOVER_ELEMENT_INVALID_MESSAGE = "Invalid route element: {element}. Must be in format backend:model"
FAILOVER_ELEMENT_NOT_FOUND_MESSAGE = "Element {element} not found in route: {route_name}"

# PWD handler messages
PWD_CURRENT_DIRECTORY_MESSAGE = "Current directory: {directory}"
PWD_DIRECTORY_NOT_SET_MESSAGE = "Project directory not set"

# Hello command messages
HELLO_COMMAND_MESSAGE = "Hello from the LLM Interactive Proxy!"

# Help command messages
HELP_AVAILABLE_COMMANDS_MESSAGE = "Available commands:"
HELP_COMMAND_NOT_FOUND_MESSAGE = "Command not found: {command}"

# Unset command messages
UNSET_PARAMETER_RESET_MESSAGE = "{parameter} reset to default"
UNSET_UNKNOWN_PARAMETER_MESSAGE = "Unknown parameter: {parameter}"
UNSET_TEMPERATURE_RESET_MESSAGE = "Temperature reset to default ({temperature})"