from __future__ import annotations

from typing import Any


class BaseObserver:
    def schedule(self, handler: Any, path: str, recursive: bool = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self, timeout: float | None = ...) -> None: ...

