from __future__ import annotations

from typing import Any

class BaseObserver:
    daemon: bool
    def schedule(self, handler: Any, path: str, recursive: bool = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_alive(self) -> bool: ...
    def join(self, timeout: float | None = ...) -> None: ...
